//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\PopupWindowImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PopupWindowImpl")
#ifdef RESTRICT_PopupWindowImpl
#define INCLUDE_ALL_PopupWindowImpl 0
#else
#define INCLUDE_ALL_PopupWindowImpl 1
#endif
#undef RESTRICT_PopupWindowImpl

#if !defined (ASPopupWindowImpl_) && (INCLUDE_ALL_PopupWindowImpl || defined(INCLUDE_ASPopupWindowImpl))
#define ASPopupWindowImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASPopupWindowImpl : ASBaseWidget {
 @public
  id uiView_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (void)addOutsideTouchListenerWithBoolean:(jboolean)add;

- (id)asNativeWidget;

- (id)asWidget;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createView;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (IOSClass *)getViewClass;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
                    withNSString:(NSString *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPopupWindowImpl)

J2OBJC_FIELD_SETTER(ASPopupWindowImpl, uiView_, id)

inline NSString *ASPopupWindowImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPopupWindowImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPopupWindowImpl, LOCAL_NAME, NSString *)

inline NSString *ASPopupWindowImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPopupWindowImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPopupWindowImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASPopupWindowImpl_init(ASPopupWindowImpl *self);

FOUNDATION_EXPORT ASPopupWindowImpl *new_ASPopupWindowImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPopupWindowImpl *create_ASPopupWindowImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASPopupWindowImpl)

@compatibility_alias ComAsheraLayoutPopupWindowImpl ASPopupWindowImpl;

#endif

#if !defined (ASPopupWindowImpl_ViewExt_) && (INCLUDE_ALL_PopupWindowImpl || defined(INCLUDE_ASPopupWindowImpl_ViewExt))
#define ASPopupWindowImpl_ViewExt_

#define RESTRICT_View 1
#define INCLUDE_ADView 1
#include "View.h"

#define RESTRICT_IViewStub 1
#define INCLUDE_ASIViewStub 1
#include "IViewStub.h"

@class ASPopupWindowImpl;

@interface ASPopupWindowImpl_ViewExt : ADView < ASIViewStub >

#pragma mark Public

- (instancetype)initWithASPopupWindowImpl:(ASPopupWindowImpl *)outer$;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)remeasure;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPopupWindowImpl_ViewExt)

FOUNDATION_EXPORT void ASPopupWindowImpl_ViewExt_initWithASPopupWindowImpl_(ASPopupWindowImpl_ViewExt *self, ASPopupWindowImpl *outer$);

FOUNDATION_EXPORT ASPopupWindowImpl_ViewExt *new_ASPopupWindowImpl_ViewExt_initWithASPopupWindowImpl_(ASPopupWindowImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPopupWindowImpl_ViewExt *create_ASPopupWindowImpl_ViewExt_initWithASPopupWindowImpl_(ASPopupWindowImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASPopupWindowImpl_ViewExt)

#endif

#pragma pop_macro("INCLUDE_ALL_PopupWindowImpl")
