//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\ProgressBarImpl.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "BaseWidget.h"
#include "Color.h"
#include "ColorStateList.h"
#include "HasWidgets.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "ProgressBar.h"
#include "ProgressBarImpl.h"
#include "Rect.h"
#include "SimpleWrapableView.h"
#include "View.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include "java/lang/Integer.h"
#include "java/lang/Float.h"
#include "java/lang/Boolean.h"
#include <UIKit/UIKit.h>
#include "HasLifeCycleDecorators.h"
#include "ASUIScrollView.h"
#include "ASUIView.h"

#include "ASUIActivityIndicatorView.h"


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASProgressBarImpl () {
 @public
  ASSimpleWrapableView *simpleWrapableView_;
  bool large_;
  id progressTint_;
}

- (void)setWidgetOnNativeClass;

- (id)getPaddingBottom;

- (id)getPaddingTop;

- (id)getPaddingRight;

- (id)getPaddingLeft;

- (id)getPaddingEnd;

- (id)getPaddingStart;

- (void)setPaddingVerticalWithId:(id)objValue;

- (void)setPaddingHorizontalWithId:(id)objValue;

- (void)setPaddingTopWithId:(id)objValue;

- (void)setPaddingEndWithId:(id)objValue;

- (void)setPaddingStartWithId:(id)objValue;

- (void)setPaddingLeftWithId:(id)objValue;

- (void)setPaddingRightWithId:(id)objValue;

- (void)setPaddingBottomWithId:(id)objValue;

- (void)setPaddingWithId:(id)objValue;

- (void)createSimpleWrapableView;

- (bool)hasScrollView;

- (bool)isViewWrapped;

- (void)setForegroundFrameWithInt:(int32_t)l
                          withInt:(int32_t)t
                          withInt:(int32_t)r
                          withInt:(int32_t)b;

- (void)invalidateWrapViewHolder;

- (id)getScrollView;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id)nativeCreateViewWithInt:(int32_t)viewType;

- (void)setProgressTintWithId:(id)objValue;

- (id)getProgressTint;

- (void)nativeMakeFrameForChildWidgetWithInt:(int32_t)l
                                     withInt:(int32_t)t
                                     withInt:(int32_t)r
                                     withInt:(int32_t)b;

@end

J2OBJC_FIELD_SETTER(ASProgressBarImpl, simpleWrapableView_, ASSimpleWrapableView *)
J2OBJC_FIELD_SETTER(ASProgressBarImpl, progressTint_, id)

inline NSString *ASProgressBarImpl_get_FOREGROUND_REGEX(void);
static NSString *ASProgressBarImpl_FOREGROUND_REGEX = @"none";
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASProgressBarImpl, FOREGROUND_REGEX, NSString *)

inline NSString *ASProgressBarImpl_get_VIEW_HOLDER_REGEX(void);
static NSString *ASProgressBarImpl_VIEW_HOLDER_REGEX = @"none";
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASProgressBarImpl, VIEW_HOLDER_REGEX, NSString *)

inline NSString *ASProgressBarImpl_get_WIDGET_REGEX(void);
static NSString *ASProgressBarImpl_WIDGET_REGEX;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASProgressBarImpl, WIDGET_REGEX, NSString *)

__attribute__((unused)) static void ASProgressBarImpl_setWidgetOnNativeClass(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getPaddingBottom(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getPaddingTop(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getPaddingRight(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getPaddingLeft(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getPaddingEnd(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getPaddingStart(ASProgressBarImpl *self);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingVerticalWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingHorizontalWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingTopWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingEndWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingStartWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingLeftWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingRightWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingBottomWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_setPaddingWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static void ASProgressBarImpl_createSimpleWrapableView(ASProgressBarImpl *self);

__attribute__((unused)) static bool ASProgressBarImpl_hasScrollView(ASProgressBarImpl *self);

__attribute__((unused)) static bool ASProgressBarImpl_isViewWrapped(ASProgressBarImpl *self);

__attribute__((unused)) static void ASProgressBarImpl_setForegroundFrameWithInt_withInt_withInt_withInt_(ASProgressBarImpl *self, int32_t l, int32_t t, int32_t r, int32_t b);

__attribute__((unused)) static void ASProgressBarImpl_invalidateWrapViewHolder(ASProgressBarImpl *self);

__attribute__((unused)) static id ASProgressBarImpl_getScrollView(ASProgressBarImpl *self);

__attribute__((unused)) static void ASProgressBarImpl_nativeCreateWithJavaUtilMap_(ASProgressBarImpl *self, id<JavaUtilMap> params);

__attribute__((unused)) static id ASProgressBarImpl_nativeCreateViewWithInt_(ASProgressBarImpl *self, int32_t viewType);

__attribute__((unused)) static void ASProgressBarImpl_setProgressTintWithId_(ASProgressBarImpl *self, id objValue);

__attribute__((unused)) static id ASProgressBarImpl_getProgressTint(ASProgressBarImpl *self);

__attribute__((unused)) static void ASProgressBarImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(ASProgressBarImpl *self, int32_t l, int32_t t, int32_t r, int32_t b);

@interface ASProgressBarImpl_ProgressBarExt () {
 @public
  WEAK_ ASProgressBarImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  int32_t mMaxWidth_;
  int32_t mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASProgressBarImpl_ProgressBarExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASProgressBarImpl_ProgressBarExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASProgressBarImpl_ProgressBarExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASProgressBarImpl_ProgressBarExt, templates_, id<JavaUtilMap>)

NSString *ASProgressBarImpl_LOCAL_NAME = @"ProgressBar";
NSString *ASProgressBarImpl_GROUP_NAME = @"ProgressBar";

@implementation ASProgressBarImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)attributeName {
  ASViewImpl_register__WithNSString_(attributeName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"iosHidesWhenStopped"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"iosColor"])) withTypeWithNSString:@"color"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"padding"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingBottom"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingRight"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingLeft"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingStart"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingEnd"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingTop"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingHorizontal"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"paddingVertical"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"progressTint"])) withTypeWithNSString:@"colorstate"]);
  ASWidgetFactory_registerConstructorAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"iosStyle"])) withTypeWithNSString:@"string"]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASProgressBarImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASProgressBarImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASProgressBarImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (IOSClass *)getViewClass {
  return ASProgressBarImpl_ProgressBarExt_class_();
}

- (id<ASIWidget>)newInstance {
  return new_ASProgressBarImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  measurableView_ = new_ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(self);
  ASProgressBarImpl_createSimpleWrapableView(self);
  ASProgressBarImpl_nativeCreateWithJavaUtilMap_(self, params);
  ASViewImpl_registerCommandConveterWithASIWidget_(self);
  ASProgressBarImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASProgressBarImpl_setWidgetOnNativeClass(self);
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id nativeWidget = [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getWrappedView];
  ASViewImpl_setAttributeWithASIWidget_withASSimpleWrapableView_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, simpleWrapableView_, key, strValue, objValue, decorator);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"iosHidesWhenStopped", @"iosColor", @"padding", @"paddingBottom", @"paddingRight", @"paddingLeft", @"paddingStart", @"paddingEnd", @"paddingTop", @"paddingHorizontal", @"paddingVertical", @"progressTint" }, 12)) {
    case 0:
    {
      [self setHidesWhenStoppedWithId:nativeWidget withId:objValue];
    }
    break;
    case 1:
    {
      [self setColorWithId:nativeWidget withId:objValue];
    }
    break;
    case 2:
    {
      ASProgressBarImpl_setPaddingWithId_(self, objValue);
    }
    break;
    case 3:
    {
      ASProgressBarImpl_setPaddingBottomWithId_(self, objValue);
    }
    break;
    case 4:
    {
      ASProgressBarImpl_setPaddingRightWithId_(self, objValue);
    }
    break;
    case 5:
    {
      ASProgressBarImpl_setPaddingLeftWithId_(self, objValue);
    }
    break;
    case 6:
    {
      ASProgressBarImpl_setPaddingStartWithId_(self, objValue);
    }
    break;
    case 7:
    {
      ASProgressBarImpl_setPaddingEndWithId_(self, objValue);
    }
    break;
    case 8:
    {
      ASProgressBarImpl_setPaddingTopWithId_(self, objValue);
    }
    break;
    case 9:
    {
      ASProgressBarImpl_setPaddingHorizontalWithId_(self, objValue);
    }
    break;
    case 10:
    {
      ASProgressBarImpl_setPaddingVerticalWithId_(self, objValue);
    }
    break;
    case 11:
    {
      ASProgressBarImpl_setProgressTintWithId_(self, objValue);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id nativeWidget = [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getWrappedView];
  id attributeValue = ASViewImpl_getAttributeWithASIWidget_withId_withASWidgetAttribute_withASILifeCycleDecorator_(self, nativeWidget, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"iosHidesWhenStopped", @"iosColor", @"paddingBottom", @"paddingRight", @"paddingLeft", @"paddingStart", @"paddingEnd", @"paddingTop", @"progressTint" }, 9)) {
    case 0:
    {
      return [self getHidesWhenStopped];
    }
    case 1:
    {
      return [self getColor];
    }
    case 2:
    {
      return ASProgressBarImpl_getPaddingBottom(self);
    }
    case 3:
    {
      return ASProgressBarImpl_getPaddingRight(self);
    }
    case 4:
    {
      return ASProgressBarImpl_getPaddingLeft(self);
    }
    case 5:
    {
      return ASProgressBarImpl_getPaddingStart(self);
    }
    case 6:
    {
      return ASProgressBarImpl_getPaddingEnd(self);
    }
    case 7:
    {
      return ASProgressBarImpl_getPaddingTop(self);
    }
    case 8:
    {
      return ASProgressBarImpl_getProgressTint(self);
    }
  }
  return nil;
}

- (id)asWidget {
  return measurableView_;
}

- (id)getPaddingBottom {
  return ASProgressBarImpl_getPaddingBottom(self);
}

- (id)getPaddingTop {
  return ASProgressBarImpl_getPaddingTop(self);
}

- (id)getPaddingRight {
  return ASProgressBarImpl_getPaddingRight(self);
}

- (id)getPaddingLeft {
  return ASProgressBarImpl_getPaddingLeft(self);
}

- (id)getPaddingEnd {
  return ASProgressBarImpl_getPaddingEnd(self);
}

- (id)getPaddingStart {
  return ASProgressBarImpl_getPaddingStart(self);
}

- (void)setPaddingVerticalWithId:(id)objValue {
  ASProgressBarImpl_setPaddingVerticalWithId_(self, objValue);
}

- (void)setPaddingHorizontalWithId:(id)objValue {
  ASProgressBarImpl_setPaddingHorizontalWithId_(self, objValue);
}

- (void)setPaddingTopWithId:(id)objValue {
  ASProgressBarImpl_setPaddingTopWithId_(self, objValue);
}

- (void)setPaddingEndWithId:(id)objValue {
  ASProgressBarImpl_setPaddingEndWithId_(self, objValue);
}

- (void)setPaddingStartWithId:(id)objValue {
  ASProgressBarImpl_setPaddingStartWithId_(self, objValue);
}

- (void)setPaddingLeftWithId:(id)objValue {
  ASProgressBarImpl_setPaddingLeftWithId_(self, objValue);
}

- (void)setPaddingRightWithId:(id)objValue {
  ASProgressBarImpl_setPaddingRightWithId_(self, objValue);
}

- (void)setPaddingBottomWithId:(id)objValue {
  ASProgressBarImpl_setPaddingBottomWithId_(self, objValue);
}

- (void)setPaddingWithId:(id)objValue {
  ASProgressBarImpl_setPaddingWithId_(self, objValue);
}

- (void)setHidesWhenStoppedWithId:(id)nativeWidget
                           withId:(id)value {
  ((ASUIActivityIndicatorView*) nativeWidget).hidesWhenStopped = [(JavaLangBoolean*) value booleanValue];
}

- (id)getHidesWhenStopped {
  return [JavaLangBoolean valueOfWithBoolean :((ASUIActivityIndicatorView*) uiView_).hidesWhenStopped];
}

- (void)setColorWithId:(id)nativeWidget
                withId:(id)value {
  ((ASUIActivityIndicatorView*) nativeWidget).color = (UIColor*) value;
}

- (id)getColor {
  return ((ASUIActivityIndicatorView*) uiView_).color;
}

- (bool)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADProgressBar *) nil_chk(measurableView_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(bool)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
    if (ASProgressBarImpl_isViewWrapped(self)) {
      ASViewImpl_invalidateWithASIWidget_withId_(self, [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getWrappedView]);
      if ([((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getForeground] != nil) {
        ASViewImpl_invalidateWithASIWidget_withId_(self, [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getForeground]);
      }
    }
  }
}

- (void)createSimpleWrapableView {
  ASProgressBarImpl_createSimpleWrapableView(self);
}

- (bool)hasScrollView {
  return ASProgressBarImpl_hasScrollView(self);
}

- (bool)isViewWrapped {
  return ASProgressBarImpl_isViewWrapped(self);
}

- (void)addForegroundIfNeeded {
  if (ASProgressBarImpl_isViewWrapped(self) && ![((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) isDisableForeground]) {
    if ([((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getForeground] == nil) {
      id foreground = [self nativeAddForeGroundWithASIWidget:self];
      ASViewGroupImpl_nativeAddViewWithId_withId_([((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) asNativeWidget], foreground);
      [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) setForegroundWithId:foreground];
    }
  }
}

- (id)getForeground {
  return [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) getForeground];
}

- (void)setForegroundFrameWithInt:(int32_t)l
                          withInt:(int32_t)t
                          withInt:(int32_t)r
                          withInt:(int32_t)b {
  ASProgressBarImpl_setForegroundFrameWithInt_withInt_withInt_withInt_(self, l, t, r, b);
}

- (id)asNativeWidget {
  return [((ASSimpleWrapableView *) nil_chk(simpleWrapableView_)) asNativeWidget];
}

- (void)invalidateWrapViewHolder {
  ASProgressBarImpl_invalidateWrapViewHolder(self);
}

- (id)createWrapperViewWithId:(id)wrapperParent
                      withInt:(int32_t)viewtype {
  uiView_ = ASProgressBarImpl_nativeCreateViewWithInt_(self, viewtype);
  ASViewGroupImpl_nativeAddViewWithId_withId_(ASViewImpl_getFirstChildOrSelfWithId_(wrapperParent), uiView_);
  return uiView_;
}

- (id)createWrapperViewHolderWithInt:(int32_t)viewType {
  return [self createWrapperViewHolderNativeWithInt:viewType];
}

- (id)nativeAddForeGroundWithASIWidget:(id<ASIWidget>)w {
  ASUIView* uiView = [ASUIView new];
  uiView.widget = w;
  uiView.commandRegex  = ASProgressBarImpl_FOREGROUND_REGEX;
  uiView.backgroundColor = [UIColor clearColor];
  return uiView;
}

- (id)createWrapperViewHolderNativeWithInt:(int32_t)viewType {
  if (viewType == 1) {
    ASUIView* uiView = [ASUIView new];
    uiView.widget = self;
    uiView.commandRegex  = ASProgressBarImpl_VIEW_HOLDER_REGEX;
    uiView.backgroundColor = [UIColor clearColor];
    
    return uiView;
  }
  
  if (viewType == 2 || viewType == 3) {
    ASUIView* uiView = [ASUIView new];
    uiView.widget = self;
    uiView.backgroundColor = [UIColor clearColor];
    uiView.commandRegex  = ASProgressBarImpl_VIEW_HOLDER_REGEX;
    
    ASUIScrollView* scrollview = [ASUIScrollView new];
    scrollview.scrollEnabled=YES;
    scrollview.bounces=NO;
    scrollview.preventAutoScroll=YES;
    scrollview.delaysContentTouches=YES;
    scrollview.userInteractionEnabled=YES;
    scrollview.widget = self;
    scrollview.backgroundColor = [UIColor clearColor];
    scrollview.commandRegex  = @"none";
    [uiView addSubview:scrollview];
    return uiView;
  }
  
  return nil;
}

- (id)getScrollView {
  return ASProgressBarImpl_getScrollView(self);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASProgressBarImpl_nativeCreateWithJavaUtilMap_(self, params);
}

- (id)nativeCreateViewWithInt:(int32_t)viewType {
  return ASProgressBarImpl_nativeCreateViewWithInt_(self, viewType);
}

- (void)setProgressTintWithId:(id)objValue {
  ASProgressBarImpl_setProgressTintWithId_(self, objValue);
}

- (id)getProgressTint {
  return ASProgressBarImpl_getProgressTint(self);
}

- (void)nativeMakeFrameForChildWidgetWithInt:(int32_t)l
                                     withInt:(int32_t)t
                                     withInt:(int32_t)r
                                     withInt:(int32_t)b {
  ASProgressBarImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(self, l, t, r, b);
}

- (int32_t)measureWidth {
  int32_t width = [((ADProgressBar *) nil_chk(measurableView_)) nativeMeasureWidthWithId:uiView_];
  return width;
}

- (int32_t)measureHeightWithInt:(int32_t)width {
  int32_t height = [((ADProgressBar *) nil_chk(measurableView_)) nativeMeasureHeightWithId:uiView_ withInt:width];
  return height;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 13, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 14, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 15, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 16, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 17, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 18, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 19, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 20, 21, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x101, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 22, 21, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x101, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 26, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 27, 28, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 31, 32, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x101, 33, 34, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x101, 35, 32, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 36, 37, -1, 38, -1, -1 },
    { NULL, "LNSObject;", 0x102, 39, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 40, 11, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 41, 28, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 42, 32, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(getViewClass);
  methods[5].selector = @selector(newInstance);
  methods[6].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[7].selector = @selector(setWidgetOnNativeClass);
  methods[8].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[9].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[10].selector = @selector(asWidget);
  methods[11].selector = @selector(getPaddingBottom);
  methods[12].selector = @selector(getPaddingTop);
  methods[13].selector = @selector(getPaddingRight);
  methods[14].selector = @selector(getPaddingLeft);
  methods[15].selector = @selector(getPaddingEnd);
  methods[16].selector = @selector(getPaddingStart);
  methods[17].selector = @selector(setPaddingVerticalWithId:);
  methods[18].selector = @selector(setPaddingHorizontalWithId:);
  methods[19].selector = @selector(setPaddingTopWithId:);
  methods[20].selector = @selector(setPaddingEndWithId:);
  methods[21].selector = @selector(setPaddingStartWithId:);
  methods[22].selector = @selector(setPaddingLeftWithId:);
  methods[23].selector = @selector(setPaddingRightWithId:);
  methods[24].selector = @selector(setPaddingBottomWithId:);
  methods[25].selector = @selector(setPaddingWithId:);
  methods[26].selector = @selector(setHidesWhenStoppedWithId:withId:);
  methods[27].selector = @selector(getHidesWhenStopped);
  methods[28].selector = @selector(setColorWithId:withId:);
  methods[29].selector = @selector(getColor);
  methods[30].selector = @selector(checkIosVersionWithNSString:);
  methods[31].selector = @selector(setIdWithNSString:);
  methods[32].selector = @selector(setVisibleWithBoolean:);
  methods[33].selector = @selector(requestLayout);
  methods[34].selector = @selector(invalidate);
  methods[35].selector = @selector(createSimpleWrapableView);
  methods[36].selector = @selector(hasScrollView);
  methods[37].selector = @selector(isViewWrapped);
  methods[38].selector = @selector(addForegroundIfNeeded);
  methods[39].selector = @selector(getForeground);
  methods[40].selector = @selector(setForegroundFrameWithInt:withInt:withInt:withInt:);
  methods[41].selector = @selector(asNativeWidget);
  methods[42].selector = @selector(invalidateWrapViewHolder);
  methods[43].selector = @selector(createWrapperViewWithId:withInt:);
  methods[44].selector = @selector(createWrapperViewHolderWithInt:);
  methods[45].selector = @selector(nativeAddForeGroundWithASIWidget:);
  methods[46].selector = @selector(createWrapperViewHolderNativeWithInt:);
  methods[47].selector = @selector(getScrollView);
  methods[48].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[49].selector = @selector(nativeCreateViewWithInt:);
  methods[50].selector = @selector(setProgressTintWithId:);
  methods[51].selector = @selector(getProgressTint);
  methods[52].selector = @selector(nativeMakeFrameForChildWidgetWithInt:withInt:withInt:withInt:);
  methods[53].selector = @selector(measureWidth);
  methods[54].selector = @selector(measureHeightWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "FOREGROUND_REGEX", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 43, -1, -1 },
    { "VIEW_HOLDER_REGEX", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 44, -1, -1 },
    { "WIDGET_REGEX", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 45, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 46, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 47, -1, -1 },
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "measurableView_", "LADProgressBar;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "simpleWrapableView_", "LASSimpleWrapableView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "large_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "progressTint_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "setPaddingVertical", "LNSObject;", "setPaddingHorizontal", "setPaddingTop", "setPaddingEnd", "setPaddingStart", "setPaddingLeft", "setPaddingRight", "setPaddingBottom", "setPadding", "setHidesWhenStopped", "LNSObject;LNSObject;", "setColor", "checkIosVersion", "setId", "setVisible", "Z", "setForegroundFrame", "IIII", "createWrapperView", "LNSObject;I", "createWrapperViewHolder", "I", "nativeAddForeGround", "LASIWidget;", "createWrapperViewHolderNative", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "nativeCreateView", "setProgressTint", "nativeMakeFrameForChildWidget", "measureHeight", &ASProgressBarImpl_FOREGROUND_REGEX, &ASProgressBarImpl_VIEW_HOLDER_REGEX, &ASProgressBarImpl_WIDGET_REGEX, &ASProgressBarImpl_LOCAL_NAME, &ASProgressBarImpl_GROUP_NAME, "LASProgressBarImpl_ProgressBarExt;" };
  static const J2ObjcClassInfo _ASProgressBarImpl = { "ProgressBarImpl", "com.ashera.layout", ptrTable, methods, fields, 7, 0x1, 55, 10, -1, 48, -1, -1, -1 };
  return &_ASProgressBarImpl;
}

@end

void ASProgressBarImpl_init(ASProgressBarImpl *self) {
  ASBaseWidget_initWithNSString_withNSString_(self, ASProgressBarImpl_GROUP_NAME, ASProgressBarImpl_LOCAL_NAME);
}

ASProgressBarImpl *new_ASProgressBarImpl_init() {
  J2OBJC_NEW_IMPL(ASProgressBarImpl, init)
}

ASProgressBarImpl *create_ASProgressBarImpl_init() {
  J2OBJC_CREATE_IMPL(ASProgressBarImpl, init)
}

void ASProgressBarImpl_initWithNSString_(ASProgressBarImpl *self, NSString *localname) {
  ASBaseWidget_initWithNSString_withNSString_(self, ASProgressBarImpl_GROUP_NAME, localname);
}

ASProgressBarImpl *new_ASProgressBarImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASProgressBarImpl, initWithNSString_, localname)
}

ASProgressBarImpl *create_ASProgressBarImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASProgressBarImpl, initWithNSString_, localname)
}

void ASProgressBarImpl_initWithNSString_withNSString_(ASProgressBarImpl *self, NSString *groupName, NSString *localname) {
  ASBaseWidget_initWithNSString_withNSString_(self, groupName, localname);
}

ASProgressBarImpl *new_ASProgressBarImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASProgressBarImpl, initWithNSString_withNSString_, groupName, localname)
}

ASProgressBarImpl *create_ASProgressBarImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASProgressBarImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASProgressBarImpl_setWidgetOnNativeClass(ASProgressBarImpl *self) {
  ((ASUIActivityIndicatorView*) self.uiView).widget = self;
}

id ASProgressBarImpl_getPaddingBottom(ASProgressBarImpl *self) {
  return JavaLangInteger_valueOfWithInt_([((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingBottom]);
}

id ASProgressBarImpl_getPaddingTop(ASProgressBarImpl *self) {
  return JavaLangInteger_valueOfWithInt_([((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingTop]);
}

id ASProgressBarImpl_getPaddingRight(ASProgressBarImpl *self) {
  return JavaLangInteger_valueOfWithInt_([((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingRight]);
}

id ASProgressBarImpl_getPaddingLeft(ASProgressBarImpl *self) {
  return JavaLangInteger_valueOfWithInt_([((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingLeft]);
}

id ASProgressBarImpl_getPaddingEnd(ASProgressBarImpl *self) {
  return ASProgressBarImpl_getPaddingRight(self);
}

id ASProgressBarImpl_getPaddingStart(ASProgressBarImpl *self) {
  return ASProgressBarImpl_getPaddingLeft(self);
}

void ASProgressBarImpl_setPaddingVerticalWithId_(ASProgressBarImpl *self, id objValue) {
  ASProgressBarImpl_setPaddingBottomWithId_(self, objValue);
  ASProgressBarImpl_setPaddingTopWithId_(self, objValue);
}

void ASProgressBarImpl_setPaddingHorizontalWithId_(ASProgressBarImpl *self, id objValue) {
  ASProgressBarImpl_setPaddingRightWithId_(self, objValue);
  ASProgressBarImpl_setPaddingLeftWithId_(self, objValue);
}

void ASProgressBarImpl_setPaddingTopWithId_(ASProgressBarImpl *self, id objValue) {
  ASViewImpl_setPaddingTopWithId_withADView_(objValue, self->measurableView_);
}

void ASProgressBarImpl_setPaddingEndWithId_(ASProgressBarImpl *self, id objValue) {
  ASViewImpl_setPaddingRightWithId_withADView_(objValue, self->measurableView_);
}

void ASProgressBarImpl_setPaddingStartWithId_(ASProgressBarImpl *self, id objValue) {
  ASViewImpl_setPaddingLeftWithId_withADView_(objValue, self->measurableView_);
}

void ASProgressBarImpl_setPaddingLeftWithId_(ASProgressBarImpl *self, id objValue) {
  ASViewImpl_setPaddingLeftWithId_withADView_(objValue, self->measurableView_);
}

void ASProgressBarImpl_setPaddingRightWithId_(ASProgressBarImpl *self, id objValue) {
  ASViewImpl_setPaddingRightWithId_withADView_(objValue, self->measurableView_);
}

void ASProgressBarImpl_setPaddingBottomWithId_(ASProgressBarImpl *self, id objValue) {
  ASViewImpl_setPaddingBottomWithId_withADView_(objValue, self->measurableView_);
}

void ASProgressBarImpl_setPaddingWithId_(ASProgressBarImpl *self, id objValue) {
  ASProgressBarImpl_setPaddingBottomWithId_(self, objValue);
  ASProgressBarImpl_setPaddingTopWithId_(self, objValue);
  ASProgressBarImpl_setPaddingRightWithId_(self, objValue);
  ASProgressBarImpl_setPaddingLeftWithId_(self, objValue);
}

void ASProgressBarImpl_createSimpleWrapableView(ASProgressBarImpl *self) {
  bool wrapViewFeature = [self hasFeatureWithNSString:@"enableFeatures" withNSString:@"decorator"];
  int32_t viewType = -1;
  if (wrapViewFeature) {
    bool hscroll = [self hasFeatureWithNSString:@"enableFeatures" withNSString:@"hscroll"];
    bool vscroll = [self hasFeatureWithNSString:@"enableFeatures" withNSString:@"vscroll"];
    viewType = 1;
    if (hscroll) viewType = 2;
    if (vscroll) viewType = 3;
  }
  self->simpleWrapableView_ = new_ASSimpleWrapableView_initWithASIWidget_withInt_(self, viewType);
}

bool ASProgressBarImpl_hasScrollView(ASProgressBarImpl *self) {
  return ASProgressBarImpl_isViewWrapped(self) && ([((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) getViewtype] == 2 || [((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) getViewtype] == 3);
}

bool ASProgressBarImpl_isViewWrapped(ASProgressBarImpl *self) {
  return [((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) isViewWrapped];
}

void ASProgressBarImpl_setForegroundFrameWithInt_withInt_withInt_withInt_(ASProgressBarImpl *self, int32_t l, int32_t t, int32_t r, int32_t b) {
  id foreground = [((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) getForeground];
  if (foreground != nil) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_(foreground, 0, 0, r - l, b - t);
  }
}

void ASProgressBarImpl_invalidateWrapViewHolder(ASProgressBarImpl *self) {
  if (ASProgressBarImpl_isViewWrapped(self)) {
    ASViewImpl_nativeInvalidateWithId_([((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) getWrapperViewHolder]);
  }
}

id ASProgressBarImpl_getScrollView(ASProgressBarImpl *self) {
  UIView* uiview = (UIView*)[self->simpleWrapableView_ getWrapperViewHolder];
  return uiview.subviews[0];
}

void ASProgressBarImpl_nativeCreateWithJavaUtilMap_(ASProgressBarImpl *self, id<JavaUtilMap> params) {
  id iosStyle = [((id<JavaUtilMap>) nil_chk(params)) getWithId:@"iosStyle"];
  self->large_ = (iosStyle == nil || [iosStyle isEqual:@"large"]);
  [((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) setDisableForegroundWithBoolean:true];
}

id ASProgressBarImpl_nativeCreateViewWithInt_(ASProgressBarImpl *self, int32_t viewType) {
  ASUIActivityIndicatorView* view;
  if (self->large_) {
    if (@available(iOS 13.0, *)) {
      view = [[ASUIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleLarge];
    } else {
      view = [[ASUIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
    }
  } else {
    if (@available(iOS 13.0, *)) {
      view = [[ASUIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];
    } else {
      view = [[ASUIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
    }
  }
  [view startAnimating];
  return view;
}

void ASProgressBarImpl_setProgressTintWithId_(ASProgressBarImpl *self, id objValue) {
  self->progressTint_ = objValue;
  if ([objValue isKindOfClass:[ADColorStateList class]]) {
    ADColorStateList *colorStateList = (ADColorStateList *) objValue;
    objValue = JavaLangInteger_valueOfWithInt_([((ADColorStateList *) nil_chk(colorStateList)) getColorForStateWithIntArray:[((ADProgressBar *) nil_chk(self->measurableView_)) getDrawableState] withInt:ADColor_RED]);
  }
  id color = ASViewImpl_getColorWithId_(objValue);
  [self setColorWithId:[self asNativeWidget] withId:color];
}

id ASProgressBarImpl_getProgressTint(ASProgressBarImpl *self) {
  return self->progressTint_;
}

void ASProgressBarImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(ASProgressBarImpl *self, int32_t l, int32_t t, int32_t r, int32_t b) {
  if (ASProgressBarImpl_isViewWrapped(self)) {
    id progressView = [((ASSimpleWrapableView *) nil_chk(self->simpleWrapableView_)) getWrappedView];
    ASViewImpl_updateBoundsWithId_withInt_withInt_withInt_withInt_(progressView, [((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingStart], [((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingTop], r - l - [((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingStart] - [((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingEnd], b - t - [((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingTop] - [((ADProgressBar *) nil_chk(self->measurableView_)) getPaddingBottom]);
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASProgressBarImpl)

J2OBJC_NAME_MAPPING(ASProgressBarImpl, "com.ashera.layout", "AS")

@implementation ASProgressBarImpl_ProgressBarExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(int32_t)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(int32_t)height {
  mMaxHeight_ = height;
}

- (int32_t)getMaxWidth {
  return mMaxWidth_;
}

- (int32_t)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASProgressBarImpl:(ASProgressBarImpl *)outer$ {
  ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
    ASProgressBarImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  }
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$0_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$0_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(int32_t)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(int32_t)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(int32_t)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (int32_t)nativeMeasureWidthWithId:(id)uiView {
  return ASViewImpl_nativeMeasureWidthWithId_(uiView);
}

- (int32_t)nativeMeasureHeightWithId:(id)uiView
                             withInt:(int32_t)width {
  return ASViewImpl_nativeMeasureHeightWithId_withInt_(uiView, width);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)__javaClone:(ASProgressBarImpl_ProgressBarExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 31, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 36, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 37, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASProgressBarImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(nativeMeasureWidthWithId:);
  methods[26].selector = @selector(nativeMeasureHeightWithId:withInt:);
  methods[27].selector = @selector(setState0WithId:);
  methods[28].selector = @selector(setState1WithId:);
  methods[29].selector = @selector(setState2WithId:);
  methods[30].selector = @selector(setState3WithId:);
  methods[31].selector = @selector(setState4WithId:);
  methods[32].selector = @selector(state0);
  methods[33].selector = @selector(state1);
  methods[34].selector = @selector(state2);
  methods[35].selector = @selector(state3);
  methods[36].selector = @selector(state4);
  methods[37].selector = @selector(stateYes);
  methods[38].selector = @selector(stateNo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASProgressBarImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 38, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 39, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASProgressBarImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "nativeMeasureWidth", "LNSObject;", "nativeMeasureHeight", "LNSObject;I", "setState0", "setState1", "setState2", "setState3", "setState4", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASProgressBarImpl_ProgressBarExt = { "ProgressBarExt", "com.ashera.layout", ptrTable, methods, fields, 7, 0x1, 39, 7, 3, -1, -1, -1, -1 };
  return &_ASProgressBarImpl_ProgressBarExt;
}

@end

void ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(ASProgressBarImpl_ProgressBarExt *self, ASProgressBarImpl *outer$) {
  self->this$0_ = outer$;
  ADProgressBar_initWithASIWidget_(self, outer$);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASProgressBarImpl_ProgressBarExt *new_ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(ASProgressBarImpl *outer$) {
  J2OBJC_NEW_IMPL(ASProgressBarImpl_ProgressBarExt, initWithASProgressBarImpl_, outer$)
}

ASProgressBarImpl_ProgressBarExt *create_ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(ASProgressBarImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASProgressBarImpl_ProgressBarExt, initWithASProgressBarImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASProgressBarImpl_ProgressBarExt)
