//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\ProgressBarImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ProgressBarImpl")
#ifdef RESTRICT_ProgressBarImpl
#define INCLUDE_ALL_ProgressBarImpl 0
#else
#define INCLUDE_ALL_ProgressBarImpl 1
#endif
#undef RESTRICT_ProgressBarImpl

#if !defined (ASProgressBarImpl_) && (INCLUDE_ALL_ProgressBarImpl || defined(INCLUDE_ASProgressBarImpl))
#define ASProgressBarImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

#define RESTRICT_ICustomMeasureHeight 1
#define INCLUDE_ASICustomMeasureHeight 1
#include "ICustomMeasureHeight.h"

#define RESTRICT_ICustomMeasureWidth 1
#define INCLUDE_ASICustomMeasureWidth 1
#include "ICustomMeasureWidth.h"

@class ADProgressBar;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASProgressBarImpl : ASBaseWidget < ASICustomMeasureHeight, ASICustomMeasureWidth > {
 @public
  id uiView_;
  ADProgressBar *measurableView_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addForegroundIfNeeded;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)createWrapperViewWithId:(id)wrapperParent
                      withInt:(jint)viewtype;

- (id)createWrapperViewHolderWithInt:(jint)viewType;

- (id)createWrapperViewHolderNativeWithInt:(jint)viewType;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getColor;

- (id)getForeground;

- (id)getHidesWhenStopped;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (jint)measureHeightWithInt:(jint)width;

- (jint)measureWidth;

- (id)nativeAddForeGroundWithASIWidget:(id<ASIWidget>)w;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setColorWithId:(id)nativeWidget
                withId:(id)value;

- (void)setHidesWhenStoppedWithId:(id)nativeWidget
                           withId:(id)value;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASProgressBarImpl)

J2OBJC_FIELD_SETTER(ASProgressBarImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASProgressBarImpl, measurableView_, ADProgressBar *)

inline NSString *ASProgressBarImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASProgressBarImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASProgressBarImpl, LOCAL_NAME, NSString *)

inline NSString *ASProgressBarImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASProgressBarImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASProgressBarImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASProgressBarImpl_init(ASProgressBarImpl *self);

FOUNDATION_EXPORT ASProgressBarImpl *new_ASProgressBarImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASProgressBarImpl *create_ASProgressBarImpl_init(void);

FOUNDATION_EXPORT void ASProgressBarImpl_initWithNSString_(ASProgressBarImpl *self, NSString *localname);

FOUNDATION_EXPORT ASProgressBarImpl *new_ASProgressBarImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASProgressBarImpl *create_ASProgressBarImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASProgressBarImpl_initWithNSString_withNSString_(ASProgressBarImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASProgressBarImpl *new_ASProgressBarImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASProgressBarImpl *create_ASProgressBarImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASProgressBarImpl)

@compatibility_alias ComAsheraLayoutProgressBarImpl ASProgressBarImpl;

#endif

#if !defined (ASProgressBarImpl_ProgressBarExt_) && (INCLUDE_ALL_ProgressBarImpl || defined(INCLUDE_ASProgressBarImpl_ProgressBarExt))
#define ASProgressBarImpl_ProgressBarExt_

#define RESTRICT_ProgressBar 1
#define INCLUDE_ADProgressBar 1
#include "ProgressBar.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADRect;
@class ADView;
@class ASProgressBarImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASProgressBarImpl_ProgressBarExt : ADProgressBar < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASProgressBarImpl:(ASProgressBarImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (jint)nativeMeasureHeightWithId:(id)uiView
                          withInt:(jint)width;

- (jint)nativeMeasureWidthWithId:(id)uiView;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADContext:(ADContext *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASProgressBarImpl_ProgressBarExt)

FOUNDATION_EXPORT void ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(ASProgressBarImpl_ProgressBarExt *self, ASProgressBarImpl *outer$);

FOUNDATION_EXPORT ASProgressBarImpl_ProgressBarExt *new_ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(ASProgressBarImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASProgressBarImpl_ProgressBarExt *create_ASProgressBarImpl_ProgressBarExt_initWithASProgressBarImpl_(ASProgressBarImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASProgressBarImpl_ProgressBarExt)

#endif

#pragma pop_macro("INCLUDE_ALL_ProgressBarImpl")
