//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\RadioGroupImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RadioGroupImpl")
#ifdef RESTRICT_RadioGroupImpl
#define INCLUDE_ALL_RadioGroupImpl 0
#else
#define INCLUDE_ALL_RadioGroupImpl 1
#endif
#undef RESTRICT_RadioGroupImpl

#if !defined (ASRadioGroupImpl_) && (INCLUDE_ALL_RadioGroupImpl || defined(INCLUDE_ASRadioGroupImpl))
#define ASRadioGroupImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

#define RESTRICT_FormElement 1
#define INCLUDE_ASFormElement 1
#include "FormElement.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASRadioGroupImpl : ASBaseHasWidgets < ASFormElement >
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)focus;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (NSString *)getTextEntered;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (jboolean)isViewVisible;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)resetError;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

- (void)showErrorWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ASRadioGroupImpl)

inline NSString *ASRadioGroupImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASRadioGroupImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASRadioGroupImpl, LOCAL_NAME, NSString *)

inline NSString *ASRadioGroupImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASRadioGroupImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASRadioGroupImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASRadioGroupImpl_init(ASRadioGroupImpl *self);

FOUNDATION_EXPORT ASRadioGroupImpl *new_ASRadioGroupImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASRadioGroupImpl *create_ASRadioGroupImpl_init(void);

FOUNDATION_EXPORT void ASRadioGroupImpl_initWithNSString_(ASRadioGroupImpl *self, NSString *localname);

FOUNDATION_EXPORT ASRadioGroupImpl *new_ASRadioGroupImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASRadioGroupImpl *create_ASRadioGroupImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASRadioGroupImpl_initWithNSString_withNSString_(ASRadioGroupImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASRadioGroupImpl *new_ASRadioGroupImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASRadioGroupImpl *create_ASRadioGroupImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASRadioGroupImpl)

@compatibility_alias ComAsheraLayoutRadioGroupImpl ASRadioGroupImpl;

#endif

#if !defined (ASRadioGroupImpl_Orientation_) && (INCLUDE_ALL_RadioGroupImpl || defined(INCLUDE_ASRadioGroupImpl_Orientation))
#define ASRadioGroupImpl_Orientation_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASRadioGroupImpl_Orientation : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASRadioGroupImpl_Orientation)

FOUNDATION_EXPORT void ASRadioGroupImpl_Orientation_init(ASRadioGroupImpl_Orientation *self);

FOUNDATION_EXPORT ASRadioGroupImpl_Orientation *new_ASRadioGroupImpl_Orientation_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASRadioGroupImpl_Orientation *create_ASRadioGroupImpl_Orientation_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASRadioGroupImpl_Orientation)

#endif

#if !defined (ASRadioGroupImpl_Divider_) && (INCLUDE_ALL_RadioGroupImpl || defined(INCLUDE_ASRadioGroupImpl_Divider))
#define ASRadioGroupImpl_Divider_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASRadioGroupImpl_Divider : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASRadioGroupImpl_Divider)

FOUNDATION_EXPORT void ASRadioGroupImpl_Divider_init(ASRadioGroupImpl_Divider *self);

FOUNDATION_EXPORT ASRadioGroupImpl_Divider *new_ASRadioGroupImpl_Divider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASRadioGroupImpl_Divider *create_ASRadioGroupImpl_Divider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASRadioGroupImpl_Divider)

#endif

#if !defined (ASRadioGroupImpl_RadioGroupExt_) && (INCLUDE_ALL_RadioGroupImpl || defined(INCLUDE_ASRadioGroupImpl_RadioGroupExt))
#define ASRadioGroupImpl_RadioGroupExt_

#define RESTRICT_RadioGroup 1
#define INCLUDE_ADRadioGroup 1
#include "RadioGroup.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASRadioGroupImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASRadioGroupImpl_RadioGroupExt : ADRadioGroup < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASRadioGroupImpl:(ASRadioGroupImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASRadioGroupImpl_RadioGroupExt)

FOUNDATION_EXPORT void ASRadioGroupImpl_RadioGroupExt_initWithASRadioGroupImpl_(ASRadioGroupImpl_RadioGroupExt *self, ASRadioGroupImpl *outer$);

FOUNDATION_EXPORT ASRadioGroupImpl_RadioGroupExt *new_ASRadioGroupImpl_RadioGroupExt_initWithASRadioGroupImpl_(ASRadioGroupImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASRadioGroupImpl_RadioGroupExt *create_ASRadioGroupImpl_RadioGroupExt_initWithASRadioGroupImpl_(ASRadioGroupImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASRadioGroupImpl_RadioGroupExt)

#endif

#pragma pop_macro("INCLUDE_ALL_RadioGroupImpl")
